// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Process from "process";

var key = Process.env.OPENAI_API_KEY;

var apiKey = (key == null) ? "default-api-key" : key;

export {
  apiKey ,
}
/* key Not a pure module */
