// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Express from "express";
import Express$1 from "express";

var app = Express$1();

app.use(Express.json());

app.get("/", (function (_req, res) {
        res.status(200).json({
              ok: true
            });
      }));

app.post("/ping", (function (req, res) {
        var body = req.body;
        var name = body.name;
        if (name == null) {
          res.status(400).json({
                error: "Missing name"
              });
        } else {
          res.status(200).json({
                message: "Hello " + name
              });
        }
      }));

app.use(function (err, _req, res, _next) {
      console.error(err);
      res.status(500).end("An error occured");
    });

app.listen(8081, (function (param) {
        console.log("Listening on http://localhost:" + String(8081));
      }));

export {
  
}
/* app Not a pure module */
