// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Express from "express";

var quizRouter = Express.Router();

quizRouter.get("/quiz", (function (_req, res) {
        res.status(200).json({
              question: "What is ReScript?"
            });
      }));

quizRouter.post("/quiz", (function (req, res) {
        var body = req.body;
        var answer = body.answer;
        if (answer == null) {
          res.status(400).json({
                error: "Missing answer"
              });
        } else {
          res.status(200).json({
                correct: answer === "A compiled language"
              });
        }
      }));

function addRoutes(app) {
  app.use("/api", quizRouter);
}

export {
  quizRouter ,
  addRoutes ,
}
/* quizRouter Not a pure module */
