// Generated by ReScript, PLEASE EDIT WITH CARE

import Express from "express";

var app = Express();

app.get("/quiz", (function (_req, res) {
        res.status(200).json({
              question: "What is ReScript?"
            });
      }));

app.post("/quiz", (function (req, res) {
        var body = req.body;
        var answer = body.answer;
        if (answer == null) {
          res.status(400).json({
                error: "Missing answer"
              });
        } else {
          res.status(200).json({
                correct: answer === "A compiled language"
              });
        }
      }));

export {
  app ,
}
/* app Not a pure module */
