// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Account(props) {
  var match = React.useState(function () {
        return true;
      });
  var setIsLogin = match[1];
  var isLogin = match[0];
  var loginForm = function () {
    return JsxRuntime.jsxs("form", {
                children: [
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("label", {
                                children: "Email",
                                className: "mb-1 text-sm font-semibold text-white",
                                htmlFor: "email"
                              }),
                          JsxRuntime.jsx("input", {
                                className: "p-2 border border-gray-300 rounded-md",
                                id: "email",
                                name: "email",
                                required: true,
                                type: "email"
                              })
                        ],
                        className: "flex flex-col"
                      }),
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("label", {
                                children: "Mot de passe",
                                className: "mb-1 text-sm font-semibold text-white",
                                htmlFor: "password"
                              }),
                          JsxRuntime.jsx("input", {
                                className: "p-2 border border-gray-300 rounded-md",
                                id: "password",
                                name: "password",
                                required: true,
                                type: "password"
                              })
                        ],
                        className: "flex flex-col"
                      }),
                  JsxRuntime.jsx("button", {
                        children: "Se connecter",
                        className: "w-full button-custom",
                        type: "submit"
                      })
                ],
                className: "space-y-4"
              });
  };
  var registerForm = function () {
    return JsxRuntime.jsxs("form", {
                children: [
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("label", {
                                children: "Nom d'utilisateur",
                                className: "mb-1 text-sm font-semibold text-white",
                                htmlFor: "username"
                              }),
                          JsxRuntime.jsx("input", {
                                className: "p-2 border border-gray-300 rounded-md",
                                id: "username",
                                name: "username",
                                required: true,
                                type: "text"
                              })
                        ],
                        className: "flex flex-col"
                      }),
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("label", {
                                children: "Email",
                                className: "mb-1 text-sm font-semibold text-white",
                                htmlFor: "email"
                              }),
                          JsxRuntime.jsx("input", {
                                className: "p-2 border border-gray-300 rounded-md",
                                id: "email",
                                name: "email",
                                required: true,
                                type: "email"
                              })
                        ],
                        className: "flex flex-col"
                      }),
                  JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("label", {
                                children: "Mot de passe",
                                className: "mb-1 text-sm font-semibold text-white",
                                htmlFor: "password"
                              }),
                          JsxRuntime.jsx("input", {
                                className: "p-2 border border-gray-300 rounded-md",
                                id: "password",
                                name: "password",
                                required: true,
                                type: "password"
                              })
                        ],
                        className: "flex flex-col"
                      }),
                  JsxRuntime.jsx("button", {
                        children: "S'inscrire",
                        className: "w-full button-custom",
                        type: "submit"
                      })
                ],
                className: "space-y-4"
              });
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h1", {
                            children: isLogin ? "Se connecter" : "S'inscrire",
                            className: "text-2xl font-bold text-center text-white mb-6"
                          }),
                      isLogin ? loginForm() : registerForm(),
                      JsxRuntime.jsx("button", {
                            children: isLogin ? "Pas de compte ? S'inscrire" : "Déjà inscrit ? Se connecter",
                            className: "w-full button-custom mt-4",
                            onClick: (function (param) {
                                setIsLogin(function (prev) {
                                      return !prev;
                                    });
                              })
                          })
                    ],
                    className: "max-w-md w-full p-6 secondary-color rounded-lg shadow-md"
                  }),
              className: "min-h-screen custom-bg flex items-center justify-center"
            });
}

var make = Account;

export {
  make ,
}
/* react Not a pure module */
