// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Quizz from "./Quizz.res.mjs";
import * as React from "react";
import * as NewQuizz from "./NewQuizz.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return null;
      });
  var setQuizQuestion = match[1];
  var quizQuestion = match[0];
  var match$1 = React.useState(function () {
        return 0;
      });
  var reset = function () {
    setQuizQuestion(function (json) {
          return null;
        });
  };
  React.useState(function () {
        return 0;
      });
  console.log(quizQuestion);
  if (!Array.isArray(quizQuestion) && (quizQuestion === null || typeof quizQuestion !== "object") && typeof quizQuestion !== "number" && typeof quizQuestion !== "string" && typeof quizQuestion !== "boolean") {
    return JsxRuntime.jsx(NewQuizz.make, {
                question: quizQuestion,
                quizHook: setQuizQuestion
              });
  } else {
    return JsxRuntime.jsx(Quizz.make, {
                quizQuestion: quizQuestion,
                score: match$1[0],
                setScore: match$1[1],
                reset: reset
              });
  }
}

var make = App;

export {
  make ,
}
/* Quizz Not a pure module */
