// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Header(props) {
  var handleButtonClick = function (path) {
    console.log("Button clicked!");
    RescriptReactRouter.push(path);
  };
  return JsxRuntime.jsxs("header", {
              children: [
                JsxRuntime.jsx("button", {
                      children: "Home",
                      className: "header-button",
                      onClick: (function (param) {
                          handleButtonClick("Home");
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "Quizz",
                      className: "header-button",
                      onClick: (function (param) {
                          handleButtonClick("Quizz");
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "NewQuizz",
                      className: "header-button",
                      onClick: (function (param) {
                          handleButtonClick("NewQuizz");
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "Account",
                      className: "header-button",
                      onClick: (function (param) {
                          handleButtonClick("Account");
                        })
                    })
              ],
              className: "header"
            });
}

var make = Header;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
