// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Home(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("img", {
                    className: "image-button",
                    alt: "Clickable button",
                    src: "../public/qvgdm.png",
                    onClick: (function (param) {
                        var path = "Account";
                        console.log("Image button clicked!");
                        RescriptReactRouter.push(path);
                      }),
                    onError: (function (param) {
                        console.log("Failed to load image");
                      })
                  }),
              className: "centered-image-button custom-bg"
            });
}

var make = Home;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
