// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function NewQuizz(props) {
  var setIter = props.setIter;
  var iter = props.iter;
  var setTopic = props.setTopic;
  var generate = props.generate;
  var themes = [
    "Sport",
    "Histoire",
    "Géographie",
    "Cinéma",
    "Musique",
    "Art",
    "Littérature",
    "Technologie",
    "South Park",
    "Shameless",
    "Futurama",
    "Brokeback Mountain"
  ];
  var randomThemes = React.useMemo((function () {
          var count = 4;
          return Belt_Array.slice(Belt_Array.shuffle(themes), 0, count);
        }), [themes]);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Nombre de questions",
                              className: "label"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("label", {
                                      children: [
                                        JsxRuntime.jsx("input", {
                                              checked: iter === 5,
                                              name: "questions",
                                              type: "radio",
                                              value: "5",
                                              onChange: (function (param) {
                                                  setIter(function (param) {
                                                        return 5;
                                                      });
                                                })
                                            }),
                                        "5"
                                      ]
                                    }),
                                JsxRuntime.jsxs("label", {
                                      children: [
                                        JsxRuntime.jsx("input", {
                                              checked: iter === 10,
                                              name: "questions",
                                              type: "radio",
                                              value: "10",
                                              onChange: (function (param) {
                                                  setIter(function (param) {
                                                        return 10;
                                                      });
                                                })
                                            }),
                                        "10"
                                      ]
                                    }),
                                JsxRuntime.jsxs("label", {
                                      children: [
                                        JsxRuntime.jsx("input", {
                                              checked: iter === 20,
                                              name: "questions",
                                              type: "radio",
                                              value: "20",
                                              onChange: (function (param) {
                                                  setIter(function (param) {
                                                        return 20;
                                                      });
                                                })
                                            }),
                                        "20"
                                      ]
                                    })
                              ],
                              className: "radio-group"
                            })
                      ],
                      className: "questions-group"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Choisissez un thème",
                              className: "label"
                            }),
                        JsxRuntime.jsx("div", {
                              children: randomThemes.map(function (theme) {
                                    return JsxRuntime.jsx("button", {
                                                children: theme,
                                                className: "answer-button",
                                                onClick: (function (param) {
                                                    var difer = async function () {
                                                      await generate(theme);
                                                      return setTopic(function (param) {
                                                                  return theme;
                                                                });
                                                    };
                                                    difer();
                                                  })
                                              });
                                  }),
                              className: "answers"
                            })
                      ],
                      className: "themes"
                    })
              ],
              className: "create-quiz-container custom-bg"
            });
}

var make = NewQuizz;

export {
  make ,
}
/* react Not a pure module */
