// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Openai from "./service/Openai.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function NewQuizz(props) {
  var quizHook = props.quizHook;
  var themes = [
    "Sport",
    "Histoire",
    "Géographie",
    "Cinéma",
    "Musique",
    "Art",
    "Littérature",
    "Technologie",
    "South Park",
    "Shameless",
    "Futurama"
  ];
  var randomThemes = React.useMemo((function () {
          var count = 4;
          return Belt_Array.slice(Belt_Array.shuffle(themes), 0, count);
        }), [themes]);
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: "Choisissez un thème",
                            className: "label"
                          }),
                      JsxRuntime.jsx("div", {
                            children: randomThemes.map(function (theme) {
                                  return JsxRuntime.jsx("button", {
                                              children: theme,
                                              className: "answer-button",
                                              onClick: (function (param) {
                                                  var generate = async function (theme) {
                                                    var newQuestion = await Openai.generateQuizQuestion(theme);
                                                    return quizHook(function (question) {
                                                                return newQuestion;
                                                              });
                                                  };
                                                  generate(theme);
                                                })
                                            });
                                }),
                            className: "answers"
                          })
                    ],
                    className: "themes"
                  }),
              className: "create-quiz-container custom-bg"
            });
}

var make = NewQuizz;

export {
  make ,
}
/* react Not a pure module */
