// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./Home.res.mjs";
import * as Quizz from "./Quizz.res.mjs";
import * as Account from "./Account.res.mjs";
import * as NewQuizz from "./NewQuizz.res.mjs";
import * as NotFound from "./NotFound.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Page(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var tmp;
  if (match) {
    switch (match.hd) {
      case "Account" :
          tmp = match.tl ? JsxRuntime.jsx(NotFound.make, {}) : JsxRuntime.jsx(Account.make, {});
          break;
      case "Home" :
          tmp = match.tl ? JsxRuntime.jsx(NotFound.make, {}) : JsxRuntime.jsx(Home.make, {});
          break;
      case "NewQuizz" :
          tmp = match.tl ? JsxRuntime.jsx(NotFound.make, {}) : JsxRuntime.jsx(NewQuizz.make, {});
          break;
      case "Quizz" :
          tmp = match.tl ? JsxRuntime.jsx(NotFound.make, {}) : JsxRuntime.jsx(Quizz.make, {});
          break;
      default:
        tmp = JsxRuntime.jsx(NotFound.make, {});
    }
  } else {
    tmp = JsxRuntime.jsx(NotFound.make, {});
  }
  return JsxRuntime.jsx("div", {
              children: tmp
            });
}

var make = Page;

export {
  make ,
}
/* Home Not a pure module */
