// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./Home.res.mjs";
import * as NotFound from "./NotFound.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Page(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var tmp;
  tmp = match && match.hd === "Home" && !match.tl ? JsxRuntime.jsx(Home.make, {}) : JsxRuntime.jsx(NotFound.make, {});
  return JsxRuntime.jsx("div", {
              children: tmp
            });
}

var make = Page;

export {
  make ,
}
/* Home Not a pure module */
