// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Quizz(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setScore = match[1];
  var answers = [
    "Paris",
    "Londres",
    "Berlin",
    "Madrid"
  ];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "Quelle est la capitale de la France?",
                              className: "question"
                            }),
                        JsxRuntime.jsx("div", {
                              children: answers.map(function (answer) {
                                    return JsxRuntime.jsx("button", {
                                                children: answer,
                                                className: "answer-button",
                                                onClick: (function (param) {
                                                    console.log(answer + " clicked!");
                                                    setScore(function (prevScore) {
                                                          return prevScore + 1 | 0;
                                                        });
                                                  })
                                              });
                                  }),
                              className: "answers"
                            })
                      ],
                      className: "flex flex-col items-center justify-start"
                    }),
                JsxRuntime.jsx("div", {
                      children: "Score: " + String(match[0]),
                      className: "score mb-4"
                    })
              ],
              className: "flex flex-col justify-between min-h-screen custom-bg"
            });
}

var make = Quizz;

export {
  make ,
}
/* react Not a pure module */
