// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as QuestionModel from "./models/QuestionModel.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Quizz(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setScore = match[1];
  var questionModel = QuestionModel.decodeQuestionModel(props.quizQuestion);
  var match$1 = questionModel !== undefined ? [
      questionModel.question,
      questionModel.options,
      questionModel.response
    ] : [
      "test",
      [{
          label: "t",
          option: "test"
        }],
      ""
    ];
  var response = match$1[2];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: match$1[0],
                              className: "question"
                            }),
                        JsxRuntime.jsx("div", {
                              children: match$1[1].map(function (answer) {
                                    return JsxRuntime.jsx("button", {
                                                children: answer.option,
                                                className: "answer-button",
                                                label: answer.label,
                                                onClick: (function (param) {
                                                    var answer$1 = answer.label;
                                                    console.log(answer$1 + " clicked!");
                                                    if (answer$1 === response) {
                                                      return setScore(function (prevScore) {
                                                                  return prevScore + 1 | 0;
                                                                });
                                                    }
                                                    
                                                  })
                                              });
                                  }),
                              className: "answers"
                            })
                      ],
                      className: "flex flex-col items-center justify-start"
                    }),
                JsxRuntime.jsx("div", {
                      children: "Score: " + String(match[0]),
                      className: "score mb-4"
                    })
              ],
              className: "flex flex-col justify-between min-h-screen custom-bg"
            });
}

var make = Quizz;

export {
  make ,
}
/* react Not a pure module */
